### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by gosteev** [enkia/enki-theme#1]
Thank you for Enki
Very promising!

Can you add some json highlighting?
Compared to material theme:

![1](https://cloud.githubusercontent.com/assets/6203574/17449613/77facbce-5b64-11e6-80ee-9e9178f6f625.png)
![2](https://cloud.githubusercontent.com/assets/6203574/17449614/77fd6550-5b64-11e6-8a79-aae36d5fa3ee.png)

**Comment by enkia** [comment]
JSON syntax has been updated and thank you for the kind remarks. Let me know what you think!

**Comment by gosteev** [comment]
awesome!
now i'll try to stick to enki.

also i can't install theme via package control, there is no package with this name

**Comment by enkia** [comment]
I'm still waiting on package control to roll it out. Hopefully it's soon!

**Comment by Electrofenster** [comment]
@enkia which plugin shows you the color under your hex variables as we can see it in this screen (first row - first item): https://packagecontrol.io/readmes/img/2fdfad1dd2bdbfa56af6539c39ae15821910ef90.png

**Comment by enkia** [comment]
@Electrofenster - [Color Highlighter](https://packagecontrol.io/packages/Color%20Highlighter.)
