### ISSUE TITLE
iTerm theme

### ISSUE THREAD

**Issue by darvid** [enkia/enki-theme#10]
A matching iTerm2 theme to Aster/Aster-red would be amazing. Love the color scheme.

**Comment by enkia** [comment]
Something like this? 
[enki-aster-red.itermcolors.zip](https://github.com/enkia/enki-theme/files/662170/enki-aster-red.itermcolors.zip)

**Comment by enkia** [comment]
Or this 
[enki-aster-red2.itermcolors.zip](https://github.com/enkia/enki-theme/files/662243/enki-aster-red2.itermcolors.zip)

**Comment by darvid** [comment]
Both are great, thank you!

**Comment by enkia** [comment]
Thanks for the idea! I may add the itermcolors files for the various schemes when I get time.

**Comment by Arelav** [comment]
https://github.com/folke/tokyonight.nvim/tree/main/extras
