### ISSUE TITLE
Folder icons in Sublime Text 3 dev build 3142

### ISSUE THREAD

**Issue by slashwhatever** [enkia/enki-theme#14]
Folder icons seem to have a background color that is at odds with the theme when using the dev build of Sublime Text 3

<img width="266" alt="screen shot 2017-08-21 at 13 39 37" src="https://user-images.githubusercontent.com/996667/29519725-51ae7ec8-8676-11e7-9a3f-82b0077bd432.png">

**Comment by enkia** [comment]
Looks like it's [A File Icon issue](https://github.com/equinusocio/material-theme/issues/1183) that'll be fixed in their new release.

**Comment by enkia** [comment]
Package Control should be rolling out the fix soon.

**Comment by alex-suarez-lmnd** [comment]
same thing here ! nothing came up on the PC
![image](https://user-images.githubusercontent.com/7695887/34328566-b7bcf096-e8af-11e7-9646-5370977c3365.png)
