### ISSUE TITLE
Ruby higlight error

### ISSUE THREAD

**Issue by larryzhao** [enkia/enki-theme#15]
With the latest update, it seems that there's a syntax highlight problem with ruby language. It will trigger the error if you divide something with an instance variable, see the following:

![image](https://user-images.githubusercontent.com/442278/30523531-83eee2c8-9ba8-11e7-80a5-461c2d285614.png)

And:
![image](https://user-images.githubusercontent.com/442278/30523535-9136fccc-9ba8-11e7-9ab4-60c63cb11212.png)

**Comment by enkia** [comment]
This appears to be an issue with ST itself. Sublime Text thinks it's a regular expression no matter what color scheme is in use. See [this forum post](https://forum.sublimetext.com/t/ruby-syntax-highlighting-failing-with-simple-test-case/28667) and [Github issue.](https://github.com/sublimehq/Packages/issues/923)  You can pull the fix if it's really bothersome.

**Comment by larryzhao** [comment]
@enkia Thx a lot!
