### ISSUE TITLE
Window font color

### ISSUE THREAD

**Issue by slashwhatever** [enkia/enki-theme#16]
Screenshot: https://puu.sh/yziJn/34ac674dcb.png

As per title, the font color in the window clashes quite badly.

MacOS High Sierra

**Comment by enkia** [comment]
Fixed (from my vantage point) 1255f8d569c44f915aa4056b70f929fe6f9cc5bb

**Comment by slashwhatever** [comment]
Unchanged for me. Screenshot: https://puu.sh/yzLax/b177eed4f3.png

**Comment by enkia** [comment]
The two screenshots are different, though. I slightly increased the brightness and the discoloration around the edges is less noticeable now. I prefer the lack of contrast so the title isn't so distracting. This is a theme I use personally; modified to suit my tastes but shared with others who may have similar. 

I believe you can set your own colors by creating a file under Packages/Enki Theme/Enki-Theme.sublime-theme and add your own color by adding this line to the file:

```
[
  {
      "class": "title_bar",
      "fg": [126, 129, 147], // Edit font color
      "bg": [32, 34, 44]
    },
]
```
