### ISSUE TITLE
Git merge conflict icons not appearing in the enki theme.

### ISSUE THREAD

**Issue by cale-sweeney** [enkia/enki-theme#18]
For sublime text 3, I am not seeing merge conflicts show up in the enki theme.  Those are the yellow fork icons in Monokai you see on the side bar when there is a merge conflict.  It would be nice to have those with the enki theme.

**Comment by enkia** [comment]
I don't use Sublime Text for heavy development anymore so I appreciate you giving me a heads up on this! I've sent out an update to Package Control. Let me know how it works out.

**Comment by cale-sweeney** [comment]
Curious, what language and IDE/text editor do you use for heavy development?

**Comment by enkia** [comment]
I use Visual Studio Code now.  I have [this theme](https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night) for that as well and just launched a new one called [Tokyo Night.](https://marketplace.visualstudio.com/items?itemName=enkia.tokyo-night)

**Comment by enkia** [comment]
Oh, and javascript and php.  :)
