### ISSUE TITLE
[Feature Request] Support for Operator Mono

### ISSUE THREAD

**Issue by apertureless** [enkia/enki-theme#2]
Hey, love your theme and color scheme. 
However it would we awesome if you could support / utilize the operator mono font.

**Comment by enkia** [comment]
Thanks for your kind words!

I haven't personally been a huge fan of the heavy use of italics in color schemes and aside from the few instances where I use it, I have no current plans to utilize it more.  I'll certainly give this some thought, though, as I've only recently acquired the Operator font. 

One quick solution for you may be to modify the scheme yourself. I supplied the YAML-tmLanguage files of the color schemes in the event that people would like to tailor them to their own display preferences.  You could create a directory, like 'Enki Theme-mod' under Packages,  copy the YAML of the color scheme you want to modify to the new directory, run [PackageDev](https://github.com/SublimeText/PackageDev) to generate the tmTheme file, and point to the new color scheme in your preferences.

**Comment by apertureless** [comment]
Okay, thanks for the response! Gonna fork it and play around a bit if you don't mind :)

**Comment by enkia** [comment]
Hit me up if/when you've come up with something you like so I can take a peak. :)
