### ISSUE TITLE
Close button image isn't being found on open files.

### ISSUE THREAD

**Issue by chaserogers** [enkia/enki-theme#5]
I fixed this locally by changing line 844 in Enki-Them.sublime-theme from `"layer0.texture": "Enki Theme/assets/default/close_icon.png",` to `"layer0.texture": "Enki Theme/assets/slate/close_icon.png",`.  Not sure if anyone else is having this issue or if it was just me but I thought I'd give you a heads up on it.  This theme is great!  Thanks!  :-)

**Comment by enkia** [comment]
Thanks for the feedback! This will get fixed in the next release.
