### ISSUE TITLE
Rename/Duplicate/Move panels not visible when using Sidebar Enhancements

### ISSUE THREAD

**Issue by jordan-trahanov** [enkia/enki-theme#7]
Hi,

First, really nice work man! Love the theme and stuff and all... 🔢 :)

There's however an issue with these panels: 

> Rename/Duplicate/Move

I' using this plug-in:

> Sidebar Enhancements

When I try to use one of these commands the panels are not visible.

I have uploaded an image to show you the issue.
The field should be in the outlined red box.
[http://i36.photobucket.com/albums/e32/bey0nd_g0dlike/screen_zpsnpkxgea6.png](http://i36.photobucket.com/albums/e32/bey0nd_g0dlike/screen_zpsnpkxgea6.png)

**Comment by enkia** [comment]
@canufeelit 

There is a known issue, [see fix here.](https://github.com/enkia/enki-theme#issues--requests--contributions)

**Comment by jordan-trahanov** [comment]
Oh, thanks!

**Comment by enkia** [comment]
No problem, thanks for the feedback!
