### ISSUE TITLE
Aster-Red color missing?

### ISSUE THREAD

**Issue by dkast** [enkia/enki-theme#9]
First of all, kudos on an this awesome theme for sublime! Now, in the last update an aster-red color scheme is mentioned, but I wasn't able to activate it from the settings, also, I use a sublime plugin called schemer that lists all my installed schemes, but also isn't listed there. Maybe I'm missing something?

**Comment by enkia** [comment]
I failed to indicate the actual color scheme name and only modified the readme file. Apologies! 

Use`"color_scheme": "Packages/Enki Theme/scheme/Enki-Aster-red.tmTheme",`

**Comment by enkia** [comment]
Apologies, Aster-red should be available now once package control updates.
